[package]
name = "polygon-iex-deep"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
etherparse = "0.8.0"
pretty_env_logger = "0.3"
pcap = "0.7"
log = "0.4"
chrono = "0.4"
chrono-tz = "0.4"
clap = "2.33.3"
sled = "0.34"
